on: push

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up GCC
      #   uses: egor-tensin/setup-gcc@v1
      #   with:
      #     version: latest
      #     platform: x64

      - name: Run tests
        run: make test
